version: 2

multi-ecosystem-groups:
  primer:
    schedule:
      interval: "daily"
      target-branch: "dev"

  octicons:
    schedule:
      interval: "daily"
      target-branch: "dev"

updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 3
    versioning-strategy: lockfile-only
    groups:
      angular:
        patterns:
          - '@angular*'
      blocknote:
        patterns:
          - '@blocknote/*'
      fullcalendar:
        patterns:
          - '@fullcalendar/*'
      html-eslint:
        patterns:
          - '@html-eslint/*'
      appsignal:
        patterns:
          - '@appsignal/*'
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    versioning-strategy: increase
    patterns:
      - "@openproject/primer-view-components"
      - "@primer/*"
    multi-ecosystem-group: "primer"

  - package-ecosystem: "npm"
    directory: "/frontend"
    versioning-strategy: increase
    patterns:
      - "@openproject/octicons-angular"
    multi-ecosystem-group: "octicons"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 3
    versioning-strategy: lockfile-only
    groups:
      aws-gems:
        patterns:
          - "aws-*"

  - package-ecosystem: "bundler"
    directory: "/"
    versioning-strategy: increase
    patterns:
      - "openproject-primer_view_components"
    multi-ecosystem-group: "primer"

  - package-ecosystem: "bundler"
    directory: "/"
    versioning-strategy: increase
    patterns:
      - "openproject-octicons*"
    multi-ecosystem-group: "octicons"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 3
