log:
  level: INFO

api:
  dashboard: true
  disabledashboardad: true

providers:
  docker:
    network: gateway
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
  websecure:
    address: ":443"
    http:
      tls:
        certresolver: step # Using step by default, overwritable via CLI

certificatesresolvers:
  step:
    acme:
      caserver: https://step:9000/acme/acme/directory
      tlschallenge: true
      email: root@localhost
      keytype: RSA4096
      storage: acme.json
  letsencrypt:
    acme:
      keytype: RSA4096
      storage: acme.json
      httpChallenge:
        entryPoint: web
