/**
 * OCM (Change Management) domain pack — ported from Kyndral DeepOCMAgent + OCMAgentAttributes.
 * Organizational change management, adoption tracking, stakeholder readiness.
 */
import type { DomainPack } from './types.js';

export const ocmPack: DomainPack = {
  agentId: 'ocm',
  capabilities: [
    'Change impact assessment',
    'Stakeholder mapping and analysis',
    'Adoption metrics tracking',
    'Intervention recommendations',
    'Resistance forecasting',
    'Multi-step change planning',
  ],
  attributes: {
    adoptionRate: { name: 'adoptionRate', displayName: 'User Adoption Rate', type: 'percentage', description: 'Percentage of target users actively adopting changes', unit: '%', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    stakeholderReadinessScore: { name: 'stakeholderReadinessScore', displayName: 'Stakeholder Readiness Score', type: 'number', description: 'Overall stakeholder readiness for change (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 60, critical: 40 } },
    changeResistanceLevel: { name: 'changeResistanceLevel', displayName: 'Change Resistance Level', type: 'enum', description: 'Level of resistance to change', values: ['low', 'moderate', 'high', 'severe'], source: 'calculated', defaultThresholds: { warning: 'high', critical: 'severe' } },
    trainingCompletionRate: { name: 'trainingCompletionRate', displayName: 'Training Completion Rate', type: 'percentage', description: 'Percentage of required training completed', unit: '%', source: 'calculated', defaultThresholds: { warning: 80, critical: 60 } },
    communicationEffectiveness: { name: 'communicationEffectiveness', displayName: 'Communication Effectiveness', type: 'number', description: 'Effectiveness of change communications (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    sponsorEngagement: { name: 'sponsorEngagement', displayName: 'Sponsor Engagement', type: 'number', description: 'Active engagement level of executive sponsors (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    impactedUsersSupportLevel: { name: 'impactedUsersSupportLevel', displayName: 'Impacted Users Support Level', type: 'percentage', description: 'Percentage of impacted users with adequate support', unit: '%', source: 'calculated', defaultThresholds: { warning: 75, critical: 60 } },
    changeReadinessGaps: { name: 'changeReadinessGaps', displayName: 'Change Readiness Gaps', type: 'number', description: 'Number of critical readiness gaps identified', unit: 'count', source: 'calculated', defaultThresholds: { warning: 3, critical: 5 } },
    change_impact_id: { name: 'change_impact_id', displayName: 'Change Impact ID', type: 'text', description: 'Identifier for specific change initiative', unit: '', source: 'project_field', defaultThresholds: {} },
    persona_impact_list: { name: 'persona_impact_list', displayName: 'Persona Impact List', type: 'text', description: 'List of roles affected by change (array)', unit: '', source: 'project_field', defaultThresholds: {} },
    adoption_velocity: { name: 'adoption_velocity', displayName: 'Adoption Velocity', type: 'number', description: 'Speed users migrate to new process/tool', unit: 'rate', source: 'calculated', defaultThresholds: { warning: 0.5, critical: 0.3 } },
    resistance_level: { name: 'resistance_level', displayName: 'Resistance Level', type: 'enum', description: 'Level of resistance to change', values: ['Low', 'Medium', 'High', 'Critical'], source: 'calculated', defaultThresholds: { warning: 'High', critical: 'Critical' } },
    sentiment_trend: { name: 'sentiment_trend', displayName: 'Sentiment Trend', type: 'enum', description: 'Sentiment direction', values: ['Improving', 'Neutral', 'Declining'], source: 'calculated', defaultThresholds: { warning: 'Declining' } },
    training_saturation: { name: 'training_saturation', displayName: 'Training Saturation', type: 'percentage', description: '% target audience completed training', unit: '%', source: 'calculated', defaultThresholds: { warning: 80, critical: 60 } },
    communication_reach: { name: 'communication_reach', displayName: 'Communication Reach', type: 'percentage', description: '% employees opened/read updates', unit: '%', source: 'external_api', defaultThresholds: { warning: 70, critical: 50 } },
    tooling_proficiency: { name: 'tooling_proficiency', displayName: 'Tooling Proficiency', type: 'percentage', description: 'Actual skill level using Jira/ADO/Miro', unit: '%', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    leadership_alignment: { name: 'leadership_alignment', displayName: 'Leadership Alignment', type: 'number', description: 'Executive "walk the talk" consistency (1-10)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 6, critical: 4 } },
    vibrancy_score: { name: 'vibrancy_score', displayName: 'Vibrancy Score', type: 'number', description: 'Activity in Slack/Teams/CoP channels', unit: 'score', source: 'external_api', defaultThresholds: { warning: 50, critical: 30 } },
    agile_mindset_delta: { name: 'agile_mindset_delta', displayName: 'Agile Mindset Delta', type: 'percentage', description: 'Growth in "Growth Mindset" surveys', unit: '%', source: 'calculated', defaultThresholds: {} },
    advocate_count: { name: 'advocate_count', displayName: 'Advocate Count', type: 'number', description: '# of "Change Champions" active in ART', unit: 'count', source: 'project_field', defaultThresholds: { warning: 3, critical: 1 } },
    benefit_awareness_pct: { name: 'benefit_awareness_pct', displayName: 'Benefit Awareness %', type: 'percentage', description: '% staff who can articulate "Why"', unit: '%', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    burnout_risk_idx: { name: 'burnout_risk_idx', displayName: 'Burnout Risk Index', type: 'number', description: 'Correlation of high Flow Load + low eNPS', unit: 'index', source: 'calculated', defaultThresholds: { warning: 0.7, critical: 0.85 } },
    transformation_fatigue: { name: 'transformation_fatigue', displayName: 'Transformation Fatigue', type: 'number', description: "Org's capacity for more change", unit: 'score', source: 'calculated', defaultThresholds: { warning: 6, critical: 8 } },
    feedback_response_time: { name: 'feedback_response_time', displayName: 'Feedback Response Time', type: 'number', description: 'How fast OCM responds to concerns (hours)', unit: 'hours', source: 'calculated', defaultThresholds: { warning: 48, critical: 72 } },
    friction_point_id: { name: 'friction_point_id', displayName: 'Friction Point ID', type: 'text', description: 'Top reason for adoption failure', unit: '', source: 'calculated', defaultThresholds: {} },
    incentive_alignment: { name: 'incentive_alignment', displayName: 'Incentive Alignment', type: 'boolean', description: 'HR goals aligned with new SAFe behaviors?', source: 'project_field', defaultThresholds: {} },
    readiness_gate_status: { name: 'readiness_gate_status', displayName: 'Readiness Gate Status', type: 'boolean', description: 'Final "Human Go" for major transition', source: 'calculated', defaultThresholds: {} },
    culture_survey_id: { name: 'culture_survey_id', displayName: 'Culture Survey ID', type: 'text', description: 'Link to latest culture assessment', unit: '', source: 'external_api', defaultThresholds: {} },
    legacy_behavior_count: { name: 'legacy_behavior_count', displayName: 'Legacy Behavior Count', type: 'number', description: '# of "Old Way" processes still used', unit: 'count', source: 'calculated', defaultThresholds: { warning: 5, critical: 10 } },
    workshop_attendance: { name: 'workshop_attendance', displayName: 'Workshop Attendance', type: 'percentage', description: '% attendance at change workshops', unit: '%', source: 'external_api', defaultThresholds: { warning: 75, critical: 60 } },
    resistance_reason_code: { name: 'resistance_reason_code', displayName: 'Resistance Reason Code', type: 'text', description: 'Coded reason for resistance', unit: '', source: 'calculated', defaultThresholds: {} },
    change_magnitude: { name: 'change_magnitude', displayName: 'Change Magnitude', type: 'number', description: 'Size of change impact (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 70, critical: 85 } },
    stakeholder_readiness_calc: { name: 'stakeholder_readiness_calc', displayName: 'Stakeholder Readiness (Calculated)', type: 'number', description: 'Readiness for change (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 60, critical: 40 } },
    awareness_level: { name: 'awareness_level', displayName: 'Awareness Level', type: 'percentage', description: '% aware of upcoming change', unit: '%', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    understanding_level: { name: 'understanding_level', displayName: 'Understanding Level', type: 'percentage', description: '% understand why change needed', unit: '%', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    acceptance_level: { name: 'acceptance_level', displayName: 'Acceptance Level', type: 'percentage', description: '% accept change is necessary', unit: '%', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    proficiency_level: { name: 'proficiency_level', displayName: 'Proficiency Level', type: 'percentage', description: '% proficient in new way', unit: '%', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    time_to_proficiency: { name: 'time_to_proficiency', displayName: 'Time to Proficiency', type: 'number', description: 'Average time to become proficient (days)', unit: 'days', source: 'calculated', defaultThresholds: { warning: 60, critical: 90 } },
  },
  rules: [
    {
      id: 'ocm-low-adoption',
      name: 'Low Adoption Rate',
      description: 'Alert when user adoption is below target',
      enabled: true,
      conditions: [{ attribute: 'adoptionRate', operator: '<', threshold: 70 }],
      actions: [
        { type: 'alert', targetAgents: ['vro'], severity: 'high', message: 'Adoption below 70% - value realization at risk' },
        { type: 'notify', targetUsers: ['ocm-lead', 'sponsor'], severity: 'high', message: 'Low adoption rate - enhanced change management interventions needed' },
      ],
    },
    {
      id: 'ocm-low-readiness',
      name: 'Low Stakeholder Readiness',
      description: 'Alert when stakeholders are not ready for change',
      enabled: true,
      conditions: [{ attribute: 'stakeholderReadinessScore', operator: '<', threshold: 50 }],
      actions: [
        { type: 'alert', targetAgents: ['vro', 'risk'], severity: 'critical', message: 'Low stakeholder readiness - adoption failure risk high' },
        { type: 'trigger_agent', targetAgents: ['strategic-pmo'], severity: 'high', message: 'Stakeholder readiness low - launch delay may be needed' },
        { type: 'notify', targetUsers: ['ocm-lead', 'sponsor'], severity: 'critical', message: 'Critical readiness gaps - accelerated readiness plan required' },
      ],
    },
    {
      id: 'ocm-high-resistance',
      name: 'High Change Resistance',
      description: 'Alert when change resistance is high',
      enabled: true,
      conditions: [{ attribute: 'changeResistanceLevel', operator: '==', threshold: 'high' }],
      actions: [
        { type: 'alert', targetAgents: ['strategic-pmo', 'vro'], severity: 'high', message: 'High change resistance - adoption and value delivery at risk' },
        { type: 'notify', targetUsers: ['ocm-lead', 'sponsor'], severity: 'high', message: 'High resistance to change - stakeholder engagement and communication needed' },
      ],
    },
    {
      id: 'ocm-severe-resistance',
      name: 'Severe Change Resistance',
      description: 'Escalate when change resistance becomes severe',
      enabled: true,
      conditions: [{ attribute: 'changeResistanceLevel', operator: '==', threshold: 'severe' }],
      actions: [
        { type: 'escalate', targetAgents: ['governance'], severity: 'critical', message: 'Severe change resistance - project viability review may be needed' },
        { type: 'trigger_agent', targetAgents: ['vro', 'risk'], severity: 'critical', message: 'Severe resistance - major value and delivery risk' },
        { type: 'notify', targetUsers: ['ocm-lead', 'sponsor', 'cxo'], severity: 'critical', message: 'Severe resistance to change - executive intervention required' },
      ],
    },
    {
      id: 'ocm-low-training-completion',
      name: 'Low Training Completion',
      description: 'Alert when training completion is below target',
      enabled: true,
      conditions: [{ attribute: 'trainingCompletionRate', operator: '<', threshold: 80 }],
      actions: [
        { type: 'alert', targetAgents: ['vro'], severity: 'medium', message: 'Training completion below 80% - competency and adoption risk' },
        { type: 'notify', targetUsers: ['ocm-lead', 'training-lead'], severity: 'medium', message: 'Low training completion - enhanced engagement strategies needed' },
      ],
    },
    {
      id: 'ocm-low-sponsor-engagement',
      name: 'Low Sponsor Engagement',
      description: 'Alert when executive sponsor engagement is insufficient',
      enabled: true,
      conditions: [{ attribute: 'sponsorEngagement', operator: '<', threshold: 70 }],
      actions: [
        { type: 'alert', targetAgents: ['strategic-pmo', 'governance'], severity: 'high', message: 'Low sponsor engagement - change credibility and resources at risk' },
        { type: 'notify', targetUsers: ['ocm-lead', 'sponsor'], severity: 'high', message: 'Executive sponsor engagement low - active sponsorship activation needed' },
      ],
    },
    {
      id: 'ocm-communication-ineffective',
      name: 'Ineffective Communications',
      description: 'Alert when change communications are not effective',
      enabled: true,
      conditions: [{ attribute: 'communicationEffectiveness', operator: '<', threshold: 70 }],
      actions: [
        { type: 'alert', targetAgents: ['vro'], severity: 'medium', message: 'Communication effectiveness low - awareness and understanding gaps' },
        { type: 'notify', targetUsers: ['ocm-lead', 'communications-lead'], severity: 'medium', message: 'Change communications ineffective - strategy revision needed' },
      ],
    },
    {
      id: 'ocm-readiness-gaps',
      name: 'Critical Readiness Gaps',
      description: 'Alert when multiple readiness gaps exist',
      enabled: true,
      conditions: [{ attribute: 'changeReadinessGaps', operator: '>', threshold: 4 }],
      actions: [
        { type: 'alert', targetAgents: ['strategic-pmo', 'risk'], severity: 'high', message: 'Multiple critical readiness gaps - launch readiness at risk' },
        { type: 'trigger_agent', targetAgents: ['vro'], severity: 'high', message: 'Readiness gaps may delay benefits realization' },
        { type: 'notify', targetUsers: ['ocm-lead', 'sponsor'], severity: 'high', message: 'Critical readiness gaps - targeted interventions required' },
      ],
    },
  ],
};

export default ocmPack;
