/**
 * TMO (Transformation) domain pack — ported from Kyndral DeepTMOAgent + TMOAgentAttributes.
 * Schedule management, timeline optimization, critical path, team health.
 */
import type { DomainPack } from './types.js';

export const tmoPack: DomainPack = {
  agentId: 'tmo',
  capabilities: [
    'Schedule variance analysis',
    'Critical path identification',
    'Resource bottleneck detection',
    'Timeline forecasting',
    'Dependency impact analysis',
    'Multi-step schedule planning',
  ],
  attributes: {
    scheduleVariance: { name: 'scheduleVariance', displayName: 'Schedule Variance', type: 'number', description: 'Days ahead or behind schedule (negative = behind)', unit: 'days', source: 'calculated', defaultThresholds: { warning: -7, critical: -14 } },
    criticalPathStatus: { name: 'criticalPathStatus', displayName: 'Critical Path Status', type: 'enum', description: 'Health status of the critical path', values: ['on-track', 'at-risk', 'delayed', 'critical'], source: 'calculated', defaultThresholds: { warning: 'at-risk', critical: 'critical' } },
    schedulePerformanceIndex: { name: 'schedulePerformanceIndex', displayName: 'Schedule Performance Index (SPI)', type: 'number', description: 'Ratio of earned value to planned value (1.0 = on schedule)', unit: 'ratio', source: 'calculated', defaultThresholds: { warning: 0.9, critical: 0.8 } },
    milestonesAtRisk: { name: 'milestonesAtRisk', displayName: 'Milestones at Risk', type: 'number', description: 'Number of milestones at risk of missing target dates', unit: 'count', source: 'calculated', defaultThresholds: { warning: 2, critical: 4 } },
    resourceUtilization: { name: 'resourceUtilization', displayName: 'Resource Utilization', type: 'percentage', description: 'Average team resource utilization rate', unit: '%', source: 'calculated', defaultThresholds: { warning: 120, critical: 150 } },
    taskCompletionRate: { name: 'taskCompletionRate', displayName: 'Task Completion Rate', type: 'percentage', description: 'Percentage of tasks completed on time', unit: '%', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    criticalPathBufferDays: { name: 'criticalPathBufferDays', displayName: 'Critical Path Buffer', type: 'number', description: 'Days of buffer remaining on critical path', unit: 'days', source: 'calculated', defaultThresholds: { warning: 5, critical: 2 } },
    dependencyRisks: { name: 'dependencyRisks', displayName: 'Dependency Risks', type: 'number', description: 'Number of blocked or at-risk task dependencies', unit: 'count', source: 'calculated', defaultThresholds: { warning: 3, critical: 6 } },
    competency_score: { name: 'competency_score', displayName: 'Competency Score', type: 'number', description: 'Team agile maturity level (0-5)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 2.5, critical: 2.0 } },
    business_agility_score: { name: 'business_agility_score', displayName: 'Business Agility Score', type: 'number', description: 'Overall business agility (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 60, critical: 40 } },
    enps_sentiment: { name: 'enps_sentiment', displayName: 'eNPS Sentiment', type: 'number', description: 'Employee Net Promoter Score (-100 to 100)', unit: 'score', source: 'external_api', defaultThresholds: { warning: 0, critical: -20 } },
    team_morale: { name: 'team_morale', displayName: 'Team Morale', type: 'number', description: 'Team satisfaction (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 60, critical: 40 } },
    psychological_safety: { name: 'psychological_safety', displayName: 'Psychological Safety', type: 'number', description: 'Team safety to speak up (0-100)', unit: 'score', source: 'external_api', defaultThresholds: { warning: 60, critical: 40 } },
    flow_load_variance: { name: 'flow_load_variance', displayName: 'Flow Load Variance', type: 'number', description: 'Variability in WIP over time', unit: 'variance', source: 'calculated', defaultThresholds: { warning: 0.3, critical: 0.5 } },
    lead_time_reduction: { name: 'lead_time_reduction', displayName: 'Lead Time Reduction', type: 'percentage', description: 'Improvement in lead time', unit: '%', source: 'calculated', defaultThresholds: {} },
    throughput: { name: 'throughput', displayName: 'Throughput', type: 'number', description: 'Work items completed per period', unit: 'count', source: 'calculated', defaultThresholds: {} },
    capacity_utilization: { name: 'capacity_utilization', displayName: 'Capacity Utilization', type: 'percentage', description: 'Actual vs available capacity', unit: '%', source: 'calculated', defaultThresholds: { warning: 85, critical: 95 } },
    capacity_forecast: { name: 'capacity_forecast', displayName: 'Capacity Forecast', type: 'text', description: 'Future capacity predictions (JSON object)', unit: '', source: 'calculated', defaultThresholds: {} },
    overtime_hours: { name: 'overtime_hours', displayName: 'Overtime Hours', type: 'number', description: 'Unplanned extra hours worked', unit: 'hours', source: 'external_api', defaultThresholds: { warning: 40, critical: 80 } },
    velocity_variance: { name: 'velocity_variance', displayName: 'Velocity Variance', type: 'percentage', description: 'Sprint-to-sprint velocity variance', unit: '%', source: 'calculated', defaultThresholds: { warning: 20, critical: 35 } },
    velocity_trend: { name: 'velocity_trend', displayName: 'Velocity Trend', type: 'enum', description: 'Velocity direction', values: ['Improving', 'Stable', 'Declining'], source: 'calculated', defaultThresholds: { warning: 'Declining' } },
    predictability: { name: 'predictability', displayName: 'Predictability', type: 'percentage', description: 'Ability to meet commitments', unit: '%', source: 'calculated', defaultThresholds: { warning: 75, critical: 60 } },
    team_size: { name: 'team_size', displayName: 'Team Size', type: 'number', description: '# of team members', unit: 'count', source: 'project_field', defaultThresholds: {} },
    team_tenure_avg: { name: 'team_tenure_avg', displayName: 'Avg Team Tenure', type: 'number', description: 'Average time on team (months)', unit: 'months', source: 'calculated', defaultThresholds: {} },
    turnover_rate: { name: 'turnover_rate', displayName: 'Turnover Rate', type: 'percentage', description: 'Annual turnover rate', unit: '%', source: 'calculated', defaultThresholds: { warning: 15, critical: 25 } },
    vacancy_count: { name: 'vacancy_count', displayName: 'Vacancy Count', type: 'number', description: 'Open positions', unit: 'count', source: 'project_field', defaultThresholds: { warning: 2, critical: 4 } },
    impediment_count: { name: 'impediment_count', displayName: 'Impediment Count', type: 'number', description: 'Active blockers', unit: 'count', source: 'external_api', defaultThresholds: { warning: 3, critical: 5 } },
    impediment_age_avg: { name: 'impediment_age_avg', displayName: 'Avg Impediment Age', type: 'number', description: 'Avg age of impediments (days)', unit: 'days', source: 'calculated', defaultThresholds: { warning: 7, critical: 14 } },
    impediment_resolution_time: { name: 'impediment_resolution_time', displayName: 'Impediment Resolution Time', type: 'number', description: 'Avg time to resolve (days)', unit: 'days', source: 'calculated', defaultThresholds: { warning: 5, critical: 10 } },
    collaboration_score: { name: 'collaboration_score', displayName: 'Collaboration Score', type: 'number', description: 'Cross-team collaboration (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 60, critical: 40 } },
    dependency_wait_time: { name: 'dependency_wait_time', displayName: 'Dependency Wait Time', type: 'number', description: 'Time waiting on dependencies (days)', unit: 'days', source: 'calculated', defaultThresholds: { warning: 3, critical: 7 } },
    skill_gap_count: { name: 'skill_gap_count', displayName: 'Skill Gap Count', type: 'number', description: '# of identified skill gaps', unit: 'count', source: 'calculated', defaultThresholds: { warning: 3, critical: 5 } },
    training_hours_per_person: { name: 'training_hours_per_person', displayName: 'Training Hours per Person', type: 'number', description: 'Annual training hours', unit: 'hours', source: 'external_api', defaultThresholds: { warning: 20, critical: 10 } },
    certification_count: { name: 'certification_count', displayName: 'Certification Count', type: 'number', description: '# of team certifications', unit: 'count', source: 'project_field', defaultThresholds: {} },
    coaching_sessions: { name: 'coaching_sessions', displayName: 'Coaching Sessions', type: 'number', description: '# coaching sessions per period', unit: 'count', source: 'external_api', defaultThresholds: {} },
    retrospective_action_items: { name: 'retrospective_action_items', displayName: 'Retrospective Action Items', type: 'number', description: 'Open retro actions', unit: 'count', source: 'project_field', defaultThresholds: { warning: 5, critical: 10 } },
    improvement_experiments: { name: 'improvement_experiments', displayName: 'Improvement Experiments', type: 'number', description: 'Active improvement experiments', unit: 'count', source: 'project_field', defaultThresholds: {} },
    metrics_dashboard_usage: { name: 'metrics_dashboard_usage', displayName: 'Metrics Dashboard Usage', type: 'percentage', description: '% team using metrics', unit: '%', source: 'external_api', defaultThresholds: { warning: 70, critical: 50 } },
  },
  rules: [
    {
      id: 'tmo-schedule-delay',
      name: 'Schedule Delay Alert',
      description: 'Alert when schedule variance exceeds acceptable threshold',
      enabled: true,
      conditions: [{ attribute: 'scheduleVariance', operator: '<', threshold: -7 }],
      actions: [
        { type: 'alert', targetAgents: ['risk'], severity: 'high', message: 'Schedule delayed by 7+ days - risk assessment needed' },
        { type: 'notify', targetUsers: ['tmo-lead', 'pmo-lead'], severity: 'high', message: 'Schedule behind - recovery plan required' },
      ],
    },
    {
      id: 'tmo-critical-path-impact',
      name: 'Critical Path Impact',
      description: 'Immediate escalation when critical path is impacted',
      enabled: true,
      conditions: [{ attribute: 'criticalPathStatus', operator: '==', threshold: 'critical' }],
      actions: [
        { type: 'escalate', targetAgents: ['governance', 'risk'], severity: 'critical', message: 'Critical path in critical state - project delivery at risk' },
        { type: 'trigger_agent', targetAgents: ['finops', 'vro'], severity: 'critical', message: 'Critical path issues - assess cost of acceleration and value impact' },
        { type: 'notify', targetUsers: ['tmo-lead', 'pmo-lead', 'sponsor'], severity: 'critical', message: 'Critical path critical - executive intervention required' },
      ],
    },
    {
      id: 'tmo-low-spi',
      name: 'Low Schedule Performance Index',
      description: 'Alert when SPI indicates schedule performance issues',
      enabled: true,
      conditions: [{ attribute: 'schedulePerformanceIndex', operator: '<', threshold: 0.9 }],
      actions: [
        { type: 'alert', targetAgents: ['strategic-pmo', 'risk'], severity: 'medium', message: 'SPI below 0.9 - schedule performance degrading' },
        { type: 'notify', targetUsers: ['tmo-lead'], severity: 'medium', message: 'Schedule performance index low - intervention needed' },
      ],
    },
    {
      id: 'tmo-buffer-exhausted',
      name: 'Critical Path Buffer Exhausted',
      description: 'Alert when critical path buffer is running out',
      enabled: true,
      conditions: [{ attribute: 'criticalPathBufferDays', operator: '<', threshold: 5 }],
      actions: [
        { type: 'alert', targetAgents: ['risk'], severity: 'high', message: 'Critical path buffer below 5 days - schedule risk increasing' },
        { type: 'trigger_agent', targetAgents: ['finops'], severity: 'high', message: 'Low schedule buffer - assess fast-track options and costs' },
        { type: 'notify', targetUsers: ['tmo-lead', 'pmo-lead'], severity: 'high', message: 'Critical path buffer low - proactive action needed' },
      ],
    },
    {
      id: 'tmo-resource-overload',
      name: 'Resource Overload',
      description: 'Alert when resource utilization indicates burnout risk',
      enabled: true,
      conditions: [{ attribute: 'resourceUtilization', operator: '>', threshold: 120 }],
      actions: [
        { type: 'alert', targetAgents: ['strategic-pmo', 'ocm'], severity: 'high', message: 'Resource utilization over 120% - team burnout risk' },
        { type: 'notify', targetUsers: ['tmo-lead', 'resource-manager'], severity: 'high', message: 'Resources overloaded - rebalancing or additional capacity needed' },
      ],
    },
    {
      id: 'tmo-milestones-at-risk',
      name: 'Multiple Milestones at Risk',
      description: 'Alert when multiple milestones are at risk',
      enabled: true,
      conditions: [{ attribute: 'milestonesAtRisk', operator: '>', threshold: 3 }],
      actions: [
        { type: 'alert', targetAgents: ['risk', 'vro'], severity: 'high', message: 'Multiple milestones at risk - delivery and value impact' },
        { type: 'trigger_agent', targetAgents: ['finops'], severity: 'medium', message: 'Milestone delays may require budget for acceleration' },
      ],
    },
    {
      id: 'tmo-dependency-risks',
      name: 'High Dependency Risks',
      description: 'Alert when too many dependencies are at risk',
      enabled: true,
      conditions: [{ attribute: 'dependencyRisks', operator: '>', threshold: 5 }],
      actions: [
        { type: 'alert', targetAgents: ['strategic-pmo', 'risk'], severity: 'high', message: 'High number of dependency risks - coordination issues' },
        { type: 'notify', targetUsers: ['tmo-lead'], severity: 'high', message: 'Dependency risks high - stakeholder alignment needed' },
      ],
    },
  ],
};

export default tmoPack;
