/**
 * VRO (Value Realization) domain pack — ported from Kyndral DeepVROAgent + VROAgentAttributes.
 * Value realization, ROI tracking, strategic alignment, benefits management.
 */
import type { DomainPack } from './types.js';

export const vroPack: DomainPack = {
  agentId: 'vro',
  capabilities: [
    'Value delivery tracking',
    'Benefits realization analysis',
    'ROI calculation and optimization',
    'Strategic alignment assessment',
    'Value trajectory forecasting',
    'Multi-step value planning',
  ],
  attributes: {
    valueScore: { name: 'valueScore', displayName: 'Overall Value Score', type: 'number', description: 'Composite value realization score (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 50, critical: 30 } },
    strategicAlignmentScore: { name: 'strategicAlignmentScore', displayName: 'Strategic Alignment Score', type: 'number', description: 'Alignment with strategic objectives and OKRs (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 50, critical: 30 } },
    projectedROI: { name: 'projectedROI', displayName: 'Projected ROI', type: 'percentage', description: 'Expected return on investment at current trajectory', unit: '%', source: 'calculated', defaultThresholds: { warning: 100, critical: 50 } },
    businessCaseHealth: { name: 'businessCaseHealth', displayName: 'Business Case Health', type: 'enum', description: 'Health status of the business case', values: ['strong', 'moderate', 'weak', 'negative'], source: 'calculated', defaultThresholds: { warning: 'weak', critical: 'negative' } },
    benefitsRealizationRate: { name: 'benefitsRealizationRate', displayName: 'Benefits Realization Rate', type: 'percentage', description: 'Percentage of planned benefits being realized', unit: '%', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    valueAtRisk: { name: 'valueAtRisk', displayName: 'Value at Risk', type: 'currency', description: 'Estimated value at risk from current issues', unit: '$', source: 'calculated', defaultThresholds: { warning: 500000, critical: 1000000 } },
    outcomeDeliveryConfidence: { name: 'outcomeDeliveryConfidence', displayName: 'Outcome Delivery Confidence', type: 'percentage', description: 'Confidence in achieving target outcomes', unit: '%', source: 'calculated', defaultThresholds: { warning: 60, critical: 40 } },
    stakeholderSatisfaction: { name: 'stakeholderSatisfaction', displayName: 'Stakeholder Satisfaction', type: 'number', description: 'Average stakeholder satisfaction score (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 60, critical: 40 } },
    strategic_theme_id: { name: 'strategic_theme_id', displayName: 'Strategic Theme ID', type: 'text', description: 'Alignment to top-level corporate goals', unit: '', source: 'project_field', defaultThresholds: {} },
    okr_key_result_link: { name: 'okr_key_result_link', displayName: 'OKR Key Result Link', type: 'text', description: 'The specific KR this work moves', unit: '', source: 'project_field', defaultThresholds: {} },
    leading_indicator_name: { name: 'leading_indicator_name', displayName: 'Leading Indicator Name', type: 'text', description: 'e.g., "Page Load Time" or "Sign-up Rate"', unit: '', source: 'project_field', defaultThresholds: {} },
    leading_indicator_baseline: { name: 'leading_indicator_baseline', displayName: 'Leading Indicator Baseline', type: 'number', description: 'Starting value before work began', unit: 'value', source: 'calculated', defaultThresholds: {} },
    leading_indicator_current: { name: 'leading_indicator_current', displayName: 'Leading Indicator Current', type: 'number', description: 'Real-time movement of indicator', unit: 'value', source: 'calculated', defaultThresholds: {} },
    hypothesis_state: { name: 'hypothesis_state', displayName: 'Hypothesis State', type: 'enum', description: 'Current state of hypothesis testing', values: ['Not Started', 'Testing', 'Proven', 'Disproven'], source: 'project_field', defaultThresholds: { warning: 'Disproven' } },
    customer_segment: { name: 'customer_segment', displayName: 'Customer Segment', type: 'text', description: 'Who is this value for?', unit: '', source: 'project_field', defaultThresholds: {} },
    nps_impact_score: { name: 'nps_impact_score', displayName: 'NPS Impact Score', type: 'number', description: 'Survey-based impact on satisfaction', unit: 'score', source: 'external_api', defaultThresholds: { warning: 0, critical: -20 } },
    value_threshold: { name: 'value_threshold', displayName: 'Value Threshold', type: 'number', description: 'Minimum Viable value needed to continue', unit: 'value', source: 'project_field', defaultThresholds: {} },
    market_share_impact: { name: 'market_share_impact', displayName: 'Market Share Impact', type: 'percentage', description: 'Estimated gain in market position', unit: '%', source: 'calculated', defaultThresholds: {} },
    adoption_rate: { name: 'adoption_rate', displayName: 'Adoption Rate', type: 'percentage', description: '% of users adopting feature', unit: '%', source: 'external_api', defaultThresholds: { warning: 50, critical: 30 } },
    churn_impact: { name: 'churn_impact', displayName: 'Churn Impact', type: 'percentage', description: 'Effect on customer churn', unit: '%', source: 'calculated', defaultThresholds: {} },
    feature_usage_daily: { name: 'feature_usage_daily', displayName: 'Feature Usage (Daily)', type: 'number', description: 'Daily active users of feature', unit: 'users', source: 'external_api', defaultThresholds: {} },
    customer_acquisition_cost: { name: 'customer_acquisition_cost', displayName: 'Customer Acquisition Cost (CAC)', type: 'currency', description: 'Cost to acquire a customer', unit: '$', source: 'calculated', defaultThresholds: {} },
    customer_lifetime_value: { name: 'customer_lifetime_value', displayName: 'Customer Lifetime Value (CLV)', type: 'currency', description: 'Lifetime value of a customer', unit: '$', source: 'calculated', defaultThresholds: {} },
    customer_retention_rate: { name: 'customer_retention_rate', displayName: 'Customer Retention Rate', type: 'percentage', description: 'Percentage of customers retained', unit: '%', source: 'calculated', defaultThresholds: { warning: 80, critical: 70 } },
    customer_satisfaction_score: { name: 'customer_satisfaction_score', displayName: 'Customer Satisfaction Score (CSAT)', type: 'number', description: 'Customer satisfaction score (0-100)', unit: 'score', source: 'external_api', defaultThresholds: { warning: 70, critical: 50 } },
    revenue_growth: { name: 'revenue_growth', displayName: 'Revenue Growth', type: 'percentage', description: 'Revenue increase attributed to feature', unit: '%', source: 'calculated', defaultThresholds: {} },
    return_on_investment: { name: 'return_on_investment', displayName: 'Return on Investment', type: 'percentage', description: 'Portfolio ROI', unit: '%', source: 'calculated', defaultThresholds: { warning: 100, critical: 50 } },
    time_to_market: { name: 'time_to_market', displayName: 'Time to Market', type: 'number', description: 'Concept to delivery time (days)', unit: 'days', source: 'calculated', defaultThresholds: { warning: 180, critical: 365 } },
    time_to_value: { name: 'time_to_value', displayName: 'Time to Value', type: 'number', description: 'Concept to customer realizes value (days)', unit: 'days', source: 'calculated', defaultThresholds: { warning: 90, critical: 180 } },
    innovation_rate: { name: 'innovation_rate', displayName: 'Innovation Rate', type: 'percentage', description: '% new features vs maintenance', unit: '%', source: 'calculated', defaultThresholds: { warning: 30, critical: 20 } },
    benefits_register: { name: 'benefits_register', displayName: 'Benefits Register', type: 'text', description: 'Array of [{benefit, target, actual, status}]', unit: '', source: 'project_field', defaultThresholds: {} },
    benefits_dependency_map: { name: 'benefits_dependency_map', displayName: 'Benefits Dependency Map', type: 'text', description: 'Benefit interdependencies (JSON object)', unit: '', source: 'project_field', defaultThresholds: {} },
    leading_indicators_list: { name: 'leading_indicators_list', displayName: 'Leading Indicators List', type: 'text', description: 'Early signals of success (array)', unit: '', source: 'project_field', defaultThresholds: {} },
    lagging_indicators_list: { name: 'lagging_indicators_list', displayName: 'Lagging Indicators List', type: 'text', description: 'Outcome measures (array)', unit: '', source: 'project_field', defaultThresholds: {} },
    benefits_realization_rate_calc: { name: 'benefits_realization_rate_calc', displayName: 'Benefits Realization Rate (Calculated)', type: 'percentage', description: '% expected benefits achieved', unit: '%', source: 'calculated', defaultThresholds: { warning: 70, critical: 50 } },
    benefit_cost_ratio: { name: 'benefit_cost_ratio', displayName: 'Benefit Cost Ratio (BCR)', type: 'number', description: 'BCR (target: >= 1.5)', unit: 'ratio', source: 'calculated', defaultThresholds: { warning: 1.5, critical: 1.0 } },
    business_value_score: { name: 'business_value_score', displayName: 'Business Value Score', type: 'number', description: 'Delivered business value (0-100)', unit: 'score', source: 'calculated', defaultThresholds: { warning: 60, critical: 40 } },
    outcome_realization_time: { name: 'outcome_realization_time', displayName: 'Outcome Realization Time', type: 'number', description: 'Time to realize outcomes (days)', unit: 'days', source: 'calculated', defaultThresholds: { warning: 90, critical: 180 } },
  },
  rules: [
    {
      id: 'vro-low-value-score',
      name: 'Low Value Score Alert',
      description: 'Alert when overall value realization is declining',
      enabled: true,
      conditions: [{ attribute: 'valueScore', operator: '<', threshold: 50 }],
      actions: [
        { type: 'escalate', targetAgents: ['governance'], severity: 'high', message: 'Value score below 50 - strategic review needed' },
        { type: 'trigger_agent', targetAgents: ['risk'], severity: 'high', message: 'Low value score - assess risks to value delivery' },
        { type: 'notify', targetUsers: ['vro-lead', 'sponsor'], severity: 'high', message: 'Value realization declining - intervention required' },
      ],
    },
    {
      id: 'vro-strategic-misalignment',
      name: 'Strategic Misalignment',
      description: 'Alert when project alignment with strategy is weak',
      enabled: true,
      conditions: [{ attribute: 'strategicAlignmentScore', operator: '<', threshold: 40 }],
      actions: [
        { type: 'escalate', targetAgents: ['governance'], severity: 'critical', message: 'Strategic misalignment detected - continuation review needed' },
        { type: 'alert', targetAgents: ['strategic-pmo'], severity: 'critical', message: 'Strategic alignment weak - portfolio impact assessment needed' },
        { type: 'notify', targetUsers: ['vro-lead', 'sponsor', 'cxo'], severity: 'critical', message: 'Strategic misalignment - executive decision required' },
      ],
    },
    {
      id: 'vro-negative-business-case',
      name: 'Negative Business Case',
      description: 'Immediate escalation when business case becomes negative',
      enabled: true,
      conditions: [{ attribute: 'businessCaseHealth', operator: '==', threshold: 'negative' }],
      actions: [
        { type: 'escalate', targetAgents: ['governance'], severity: 'critical', message: 'Business case negative - project viability review required' },
        { type: 'trigger_agent', targetAgents: ['finops', 'risk'], severity: 'critical', message: 'Negative business case - assess financial and strategic implications' },
        { type: 'notify', targetUsers: ['vro-lead', 'sponsor', 'cfo'], severity: 'critical', message: 'Business case negative - project continuation decision needed' },
      ],
    },
    {
      id: 'vro-low-roi',
      name: 'Low Projected ROI',
      description: 'Alert when projected ROI falls below acceptable threshold',
      enabled: true,
      conditions: [{ attribute: 'projectedROI', operator: '<', threshold: 100 }],
      actions: [
        { type: 'alert', targetAgents: ['finops'], severity: 'high', message: 'Projected ROI below 100% - cost optimization assessment needed' },
        { type: 'notify', targetUsers: ['vro-lead', 'finops-lead'], severity: 'high', message: 'Low projected ROI - value enhancement strategies needed' },
      ],
    },
    {
      id: 'vro-high-value-at-risk',
      name: 'High Value at Risk',
      description: 'Alert when significant value is at risk',
      enabled: true,
      conditions: [{ attribute: 'valueAtRisk', operator: '>', threshold: 1000000 }],
      actions: [
        { type: 'escalate', targetAgents: ['governance', 'risk'], severity: 'critical', message: 'Value at risk exceeds $1M - mitigation required' },
        { type: 'trigger_agent', targetAgents: ['tmo', 'finops'], severity: 'critical', message: 'High value at risk - assess recovery options and costs' },
        { type: 'notify', targetUsers: ['vro-lead', 'sponsor'], severity: 'critical', message: 'Significant value at risk - immediate action needed' },
      ],
    },
    {
      id: 'vro-low-benefits-realization',
      name: 'Low Benefits Realization',
      description: 'Alert when benefits realization is below target',
      enabled: true,
      conditions: [{ attribute: 'benefitsRealizationRate', operator: '<', threshold: 70 }],
      actions: [
        { type: 'alert', targetAgents: ['ocm', 'strategic-pmo'], severity: 'high', message: 'Benefits realization below 70% - adoption and delivery issues' },
        { type: 'notify', targetUsers: ['vro-lead'], severity: 'high', message: 'Low benefits realization - review realization plan' },
      ],
    },
    {
      id: 'vro-low-delivery-confidence',
      name: 'Low Outcome Delivery Confidence',
      description: 'Alert when confidence in achieving outcomes is low',
      enabled: true,
      conditions: [{ attribute: 'outcomeDeliveryConfidence', operator: '<', threshold: 60 }],
      actions: [
        { type: 'alert', targetAgents: ['risk', 'strategic-pmo'], severity: 'high', message: 'Low delivery confidence - risk assessment and plan review needed' },
        { type: 'notify', targetUsers: ['vro-lead', 'sponsor'], severity: 'high', message: 'Confidence in outcome delivery low - intervention needed' },
      ],
    },
    {
      id: 'vro-stakeholder-dissatisfaction',
      name: 'Stakeholder Dissatisfaction',
      description: 'Alert when stakeholder satisfaction is low',
      enabled: true,
      conditions: [{ attribute: 'stakeholderSatisfaction', operator: '<', threshold: 50 }],
      actions: [
        { type: 'alert', targetAgents: ['ocm', 'strategic-pmo'], severity: 'high', message: 'Low stakeholder satisfaction - engagement issues' },
        { type: 'notify', targetUsers: ['vro-lead', 'sponsor'], severity: 'high', message: 'Stakeholder satisfaction low - communication and alignment needed' },
      ],
    },
  ],
};

export default vroPack;
