services:
  hocuspocus:
    image:  openproject/hocuspocus:main-88913ad0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hocuspocus.rule=Host(`hocuspocus.local`)"
      - "traefik.http.routers.hocuspocus.service=hocuspocus-service"
      - "traefik.http.routers.hocuspocus.tls=true"
      - "traefik.http.services.hocuspocus-service.loadbalancer.server.port=1234"
      - "traefik.http.routers.hocuspocus.tls.certresolver=step"
    networks:
      - gateway
    environment:
      - SECRET=secret12345
networks:
  gateway:
    external: true
    name: gateway
volumes:
  node_modules:
