/**
 * Vercel AI SDK (v5) tool set over the agent-runtime sidecar.
 *
 * Every tool returns STRUCTURED data (never prose) so the client can render it
 * as typed widgets — the numbers the user sees on screen come from the graph's
 * computed/validated endpoints, not from the LLM's text. The model's job is to
 * explain and prioritize (GROUNDING_AND_HALLUCINATION.md §5), never to invent.
 *
 * Read tools:    getPortfolioMetrics, getFindings, getAgentRoster,
 *                getAgentTrackRecord, getProjectStatus
 * Acting tools:  approveFinding, rejectFinding (HITL decisions — only on an
 *                explicit user request), triggerSweep
 *
 * Usage (server route): pass `agenticTools` + `AGENTIC_SYSTEM_PROMPT` to
 * streamText — see ./routes/agentChat.route.ts.
 */
import { tool } from "ai";
import { z } from "zod";
import {
  getAgentRuntimeClient,
  parseEvidence,
  parseFindingMetrics,
  type EvidenceItem,
  type Finding,
  type Metric,
} from "./agentRuntimeClient";

// ── Structured tool outputs (the widget contracts) ──────────────────────────

/** A finding flattened for display: evidence parsed, narrative preferred. */
export interface FindingView {
  id: string;
  agentId: string;
  type: string;
  severity: string;
  status: string;
  title: string;
  /** Narrative if present, else the deterministic body. */
  summary: string;
  /** True when `summary` is the LLM narrative (UI tags it "AI narrative"). */
  isNarrative: boolean;
  /** Agent-reported, grounding-adjusted confidence 0–1; 0 = not reported. */
  confidence: number;
  /** Parsed evidence citations — entityId · metric = value. */
  evidence: EvidenceItem[];
  projectId?: number;
  projectName?: string;
  workPackageId?: number;
  updatedAt: string;
  decidedBy?: string;
}

export interface TrackRecordEntry {
  agentId: string;
  /** Human-facing name from the roster (agentId if unknown). */
  name: string;
  total: number;
  correct: number;
  incorrect: number;
  humanConfirmed: number;
  humanRejected: number;
  /** 0–1, or null when fewer than 3 resolved predictions (honest n/a). */
  accuracy: number | null;
}

export interface ProjectStatusItem {
  projectId?: number;
  projectName?: string;
  severity: string;
  title: string;
  summary: string;
  /** Computed-metrics snapshot attached to the assessment (scalar metrics). */
  metrics: Metric[];
  updatedAt: string;
}

export interface DecisionOutput {
  ok: boolean;
  findingId: string;
  decision: "approved" | "rejected";
  status?: string;
  decidedBy?: string;
  /** Detail of the gated action executed on approval (e.g. follow-up WP). */
  actionDetail?: string;
  followupWpId?: number;
  error?: string;
}

function toFindingView(f: Finding): FindingView {
  const narrative = (f.narrative ?? "").trim();
  return {
    id: f.id,
    agentId: f.agentId,
    type: f.type,
    severity: f.severity,
    status: f.status,
    title: f.title,
    summary: narrative || f.body,
    isNarrative: narrative.length > 0,
    confidence: f.confidence ?? 0,
    evidence: parseEvidence(f.evidence),
    projectId: f.projectId || undefined,
    projectName: f.projectName || undefined,
    workPackageId: f.workPackageId || undefined,
    updatedAt: f.updatedAt,
    decidedBy: f.decidedBy || undefined,
  };
}

// ── Tools ────────────────────────────────────────────────────────────────────

const getPortfolioMetrics = tool({
  description:
    "Get the portfolio-wide COMPUTED metrics (open items, overdue count/%, unassigned " +
    "high-priority, per-project progress, assignee load, status distribution). These are " +
    "deterministic aggregates computed from the graph — NOT generated by an LLM. Each metric " +
    "carries an id and a formula. When discussing numbers, cite the metric ids (e.g. " +
    "[overduePct]) and use the returned values verbatim. NEVER invent or extrapolate numbers " +
    "that are not in this output.",
  inputSchema: z.object({}),
  execute: async () => {
    const m = await getAgentRuntimeClient().getMetrics();
    return {
      computedAt: m.computedAt,
      metrics: m.metrics,
      channel: "computed" as const,
      ...(m.error ? { error: m.error } : {}),
    };
  },
});

const getFindings = tool({
  description:
    "List agent findings (delivery-risk, governance, capacity, cost detections). Each finding " +
    "carries evidence citations (entityId · metric = value) and a grounding-adjusted confidence " +
    "score. Filter by status ('open' = new+published awaiting human review, 'approved', " +
    "'rejected', 'resolved'), by agentId, and/or by severity (high|medium|low). When summarizing " +
    "a finding, ground every claim in its evidence list; if evidence is empty or confidence is " +
    "low, say so rather than embellishing.",
  inputSchema: z.object({
    status: z
      .enum(["open", "new", "published", "approved", "rejected", "resolved"])
      .optional()
      .describe("Lifecycle filter; default 'open' (awaiting human review)."),
    agentId: z.string().optional().describe("Filter to one agent (e.g. 'strategic-pmo', 'finops')."),
    severity: z.enum(["high", "medium", "low"]).optional().describe("Filter by severity."),
  }),
  execute: async ({ status, agentId, severity }) => {
    const findings = await getAgentRuntimeClient().getFindings({ status: status ?? "open", agentId });
    const filtered = severity ? findings.filter((f) => f.severity === severity) : findings;
    return { count: filtered.length, findings: filtered.map(toFindingView) };
  },
});

const getAgentRoster = tool({
  description:
    "List the agent roster — each agent's domain, purpose, the detection types it owns, and its " +
    "open/total finding counts. Use this to explain which agent is responsible for what.",
  inputSchema: z.object({}),
  execute: async () => {
    const roster = await getAgentRuntimeClient().getRoster();
    return { agents: roster };
  },
});

const getAgentTrackRecord = tool({
  description:
    "Get each agent's PROVABLE track record: predictions resolved against real outcomes (graph " +
    "state + human approve/reject labels). accuracy is 0–1 over resolved predictions, or null " +
    "when fewer than 3 are resolved — report null honestly as 'not enough resolved predictions " +
    "yet', never as a made-up percentage. Example of a correct claim: '84% accurate over 12 " +
    "resolved predictions'. Also returns the most recently resolved predictions.",
  inputSchema: z.object({}),
  execute: async () => {
    const client = getAgentRuntimeClient();
    const [learning, roster] = await Promise.all([
      client.getLearning(),
      client.getRoster().catch(() => []),
    ]);
    const names = new Map(roster.map((a) => [a.id, a.name]));
    const agents: TrackRecordEntry[] = Object.entries(learning.accuracy).map(([agentId, a]) => ({
      agentId,
      name: names.get(agentId) ?? agentId,
      ...a,
    }));
    agents.sort((x, y) => y.total - x.total);
    return { agents, recent: learning.recent };
  },
});

const getProjectStatus = tool({
  description:
    "Get the latest per-project portfolio assessment (the banner-quality status each project " +
    "shows). Each item carries the computed-metrics snapshot the assessment was grounded in — " +
    "cite those numbers, do not restate them from memory. Optionally filter to one projectId.",
  inputSchema: z.object({
    projectId: z.number().optional().describe("OpenProject project id to filter to."),
  }),
  execute: async ({ projectId }) => {
    const all = await getAgentRuntimeClient().getProjectStatus();
    const filtered = projectId ? all.filter((f) => f.projectId === projectId) : all;
    const items: ProjectStatusItem[] = filtered.map((f) => ({
      projectId: f.projectId || undefined,
      projectName: f.projectName || undefined,
      severity: f.severity,
      title: f.title,
      summary: (f.narrative ?? "").trim() || f.body,
      metrics: parseFindingMetrics(f.metrics),
      updatedAt: f.updatedAt,
    }));
    return { count: items.length, items };
  },
});

const approveFinding = tool({
  description:
    "ACTS ON THE SYSTEM: approve a finding (human-in-the-loop decision). Approval executes the " +
    "gated action (e.g. creates a follow-up work package), records the human-confirmed learning " +
    "label, and comments back into OpenProject. ONLY call this when the user has EXPLICITLY " +
    "asked to approve this specific finding in this conversation — never approve proactively, " +
    "never batch-approve without the user naming each finding.",
  inputSchema: z.object({
    findingId: z.string().describe("The finding id to approve (from getFindings)."),
    reason: z.string().optional().describe("Optional short reason, recorded in the audit trail."),
  }),
  execute: async ({ findingId, reason }): Promise<DecisionOutput> => {
    const decidedBy = reason ? `agent-chat (${reason})` : "agent-chat";
    try {
      const r = await getAgentRuntimeClient().decideFinding(findingId, "approve", decidedBy);
      return {
        ok: true,
        findingId,
        decision: "approved",
        status: r.status,
        decidedBy: r.decidedBy ?? decidedBy,
        actionDetail: r.action?.detail,
        followupWpId: r.action?.followupWpId ?? undefined,
      };
    } catch (err) {
      return { ok: false, findingId, decision: "approved", error: err instanceof Error ? err.message : String(err) };
    }
  },
});

const rejectFinding = tool({
  description:
    "ACTS ON THE SYSTEM: reject a finding (human-in-the-loop decision). Rejection records the " +
    "human-rejected learning label (which lowers the agent's track record) and comments back " +
    "into OpenProject; no action is taken. ONLY call this when the user has EXPLICITLY asked to " +
    "reject this specific finding in this conversation.",
  inputSchema: z.object({
    findingId: z.string().describe("The finding id to reject (from getFindings)."),
    reason: z.string().optional().describe("Optional short reason, recorded in the audit trail."),
  }),
  execute: async ({ findingId, reason }): Promise<DecisionOutput> => {
    const decidedBy = reason ? `agent-chat (${reason})` : "agent-chat";
    try {
      const r = await getAgentRuntimeClient().decideFinding(findingId, "reject", decidedBy);
      return {
        ok: true,
        findingId,
        decision: "rejected",
        status: r.status,
        decidedBy: r.decidedBy ?? decidedBy,
      };
    } catch (err) {
      return { ok: false, findingId, decision: "rejected", error: err instanceof Error ? err.message : String(err) };
    }
  },
});

const triggerSweep = tool({
  description:
    "Run the detector sweep on demand: re-runs the deterministic detectors over the graph, " +
    "records deduped findings, and publishes new ones to the OpenProject inbox. Use when the " +
    "user asks for a fresh scan. Returns counts only — follow with getFindings to see results.",
  inputSchema: z.object({}),
  execute: async () => getAgentRuntimeClient().triggerSweep(),
});

/** The full tool set for streamText({ tools: agenticTools }). */
export const agenticTools = {
  getPortfolioMetrics,
  getFindings,
  getAgentRoster,
  getAgentTrackRecord,
  getProjectStatus,
  approveFinding,
  rejectFinding,
  triggerSweep,
};

export type AgenticTools = typeof agenticTools;

// ── System prompt: the trust narrative as operating rules ───────────────────

export const AGENTIC_SYSTEM_PROMPT = `You are the Kyndral-365 portfolio assistant, grounded in a live agent runtime over the portfolio graph.

How this system earns trust — and the rules you must follow:

1. METRICS ARE COMPUTED, NOT GENERATED. Every number comes from deterministic formulas run on the source data (the getPortfolioMetrics / getProjectStatus tools). You must NEVER invent, estimate, round differently, or extrapolate a number. Use tool outputs verbatim and reference metrics by their id (e.g. [overduePct], [totalOpenItems]) so they are auditable.

2. CITE EVIDENCE. Findings carry evidence citations ({entityId, metric, value}) and a grounding-adjusted confidence score. When you explain a finding, point at its evidence. Do not add claims the evidence does not support.

3. ABSTAIN ON THIN DATA. If a tool returns no data, empty evidence, low confidence, or accuracy: null (fewer than 3 resolved predictions), say "insufficient data" or "no track record yet" plainly. An honest "I don't know" beats a confident guess, always.

4. TRACK RECORDS ARE PROVABLE. Agent accuracy comes from predictions resolved against real outcomes and human approve/reject labels (getAgentTrackRecord). Quote it precisely — "84% accurate over 12 resolved predictions" — never as a vibe.

5. HUMANS DECIDE. approveFinding / rejectFinding act on the real system (OpenProject comments, follow-up work packages, learning labels). Only call them when the user explicitly requests that decision on that specific finding, and confirm what happened afterwards from the tool result.

6. YOUR JOB IS TO EXPLAIN AND PRIORITIZE — what the numbers mean, what to look at first, what the trade-offs are. The facts come from the tools; the judgment and clarity come from you. The UI renders tool outputs as widgets, so keep your text complementary: interpret, compare, recommend — don't re-list every number the widget already shows.`;
