# frozen_string_literal: true

#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

module OpenProject::TextFormatting
  module Filters
    # Builds a Table of Contents from headings generated by Commonmarker.
    #
    # Commonmarker (with our default options) emits:
    #   <h1><a href="#slug" aria-hidden="true" class="anchor" id="slug"></a>Heading text</h1>
    #
    # This filter:
    #   1. Styles the permalink anchor inside each heading.
    #   2. Collects heading level, anchor href and heading text.
    #   3. Exposes result[:toc] with the rendered TOC nav HTML (used by the Toc macro).
    #
    # Note: FragmentIdPrefixFilter must run before this filter so the anchor
    # hrefs already carry the "op-frag-" prefix when we collect them.
    class TableOfContentsFilter < HTMLPipeline::NodeFilter
      include ActionView::Context
      include ActionView::Helpers::TagHelper

      # Match heading and anchor-inside-heading elements, plus heading text.
      SELECTOR = Selma::Selector.new(
        match_element: "h1, h2, h3, h4, h5, h6, h1 a, h2 a, h3 a, h4 a, h5 a, h6 a",
        match_text_within: "h1, h2, h3, h4, h5, h6"
      )

      def selector
        SELECTOR
      end

      def after_initialize
        @headings      = []   # Array of {level:, href:, text:}
        @current_level = nil
        @current_href  = nil
        @current_text  = +""
      end

      def reset!
        after_initialize
      end

      def handle_element(element)
        name = element.tag_name

        if (m = name.match(/\Ah([1-6])\z/))
          # Opening a new heading — finalise the previous one first.
          push_heading
          @current_level = m[1].to_i
          @current_href  = nil
          @current_text  = +""
        elsif name == "a" && @current_level
          # Permalink anchor generated by Commonmarker inside the current heading.
          href = element["href"]
          if href&.start_with?("#")
            @current_href = href
            # Style the anchor as a permalink.
            element["class"] = "op-uc-link_permalink icon-link"
          end
        end
      end

      def handle_text_chunk(text)
        return unless @current_level

        @current_text << text.to_s
      end

      # Override result so the TOC is built on demand after traversal completes,
      # rather than requiring an explicit after_call hook (which Selma does not provide).
      def result
        push_heading  # finalise the last heading if any
        @result.merge(toc: build_toc_html)
      end

      private

      def push_heading
        return unless @current_level && @current_href && @current_text.present?

        @headings << {
          level: @current_level,
          href:  @current_href,
          text:  @current_text.dup
        }
        @current_level = nil
        @current_href  = nil
        @current_text  = +""
      end

      # Build the TOC nav as an HTML string.
      def build_toc_html
        return I18n.t(:label_wiki_toc_empty) if @headings.empty?

        content_tag(:nav, class: "op-uc-toc") do
          content_tag(:ul, class: "op-uc-toc--list") do
            render_nested(@headings.dup)
          end
        end
      rescue StandardError => e
        Rails.logger.error { "Failed to render table of contents: #{e} #{e.message}" }
        ""
      end

      # Recursively build nested <ul>/<li> structure.
      def render_nested(headings, level = nil, parent_number = "") # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
        result_html  = +"".html_safe
        num_in_level = 0

        while headings.any?
          node_level = headings.first[:level]
          level ||= node_level

          if level == node_level
            heading = headings.shift
            num_in_level += 1
            current_number = heading_number(parent_number, num_in_level)
            result_html << toc_item(heading, current_number)
          elsif level < node_level
            result_html << (content_tag(:ul, class: "op-uc-toc--list") do
              render_nested(headings, node_level,
                            num_in_level > 0 ? heading_number(parent_number, num_in_level) : "")
            end)
          else
            break
          end
        end

        result_html
      end

      def toc_item(heading, number)
        content_tag(:li, class: "op-uc-toc--list-item") do
          anchor_link(heading[:text], heading[:href], number)
        end
      end

      def heading_number(parent, num)
        parent.blank? ? num.to_s : "#{parent}.#{num}"
      end

      def anchor_link(text, href, number)
        parsed      = text.match(Regexp.new("^(#{Regexp.escape(number)}[.)]*)?(.+)$"))
        num_part    = parsed ? (parsed[1] || number) : number
        title_part  = parsed ? parsed[2].strip : text.strip

        number_span = content_tag(:span, num_part,   class: "op-uc-toc--list-item-number")
        title_span  = content_tag(:span, title_part, class: "op-uc-toc--list-item-title")
        content_tag(:a, number_span + title_span, href:, class: "op-uc-toc--item-link")
      end
    end
  end
end
