services:
  youtrack:
    image:  jetbrains/youtrack:2025.2.98373
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.youtrack.rule=Host(`youtrack.${OPENPROJECT_DOCKER_DEV_TLD}`)"
      - "traefik.http.routers.youtrack.service=youtrack-service"
      - "traefik.http.services.youtrack-service.loadbalancer.server.port=8080"
    networks:
      - gateway
    volumes:
      - youtrack-data:/opt/youtrack/data
      - youtrack-conf:/opt/youtrack/conf
      - youtrack-logs:/opt/youtrack/logs
      - youtrack-backups:/opt/youtrack/backups
networks:
  gateway:
    external: true
    name: gateway
volumes:
  youtrack-data:
  youtrack-conf:
  youtrack-logs:
  youtrack-backups:
