# frozen_string_literal: true

#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

class LongRunningTask < ApplicationRecord
  belongs_to :created_by, class_name: "User", optional: true

  enum :task_type, { semantic_id_conversion: 0, semantic_id_reversion: 1 }, validate: true
  enum :status, { pending: 0, processing: 10, complete: 20, failed: 30, aborted: 40 }

  before_create { self.created_by ||= User.current }

  TRANSITIONS = { "pending" => %w[processing aborted],
                  "processing" => %w[complete failed aborted],
                  "complete" => [],
                  "failed" => [],
                  "aborted" => [] }.freeze

  # pending, processing, complete, failed scopes are auto-generated by enum.
  scope :in_progress, -> { where(status: %i[pending processing]) }

  def start!
    transition_to!("processing") { update!(status: :processing, started_at: Time.current) }
  end

  def complete!(result = {})
    transition_to!("complete") { update!(status: :complete, completed_at: Time.current, result:) }
  end

  def fail!(result = {})
    transition_to!("failed") { update!(status: :failed, failed_at: Time.current, result:) }
  end

  def abort!(result = {})
    transition_to!("aborted") { update!(status: :aborted, aborted_at: Time.current, result:) }
  end

  private

  def transition_to!(new_status)
    unless TRANSITIONS[status].include?(new_status)
      raise ArgumentError, "Invalid transition for #{task_type}: #{status} → #{new_status}"
    end

    yield
  end
end
