#!/usr/bin/env ruby
# frozen_string_literal: true

# Backfill Jira project memberships and roles into OpenProject.
#
# Expected inputs:
# - project membership CSVs from Jira export
# - identity mapping files generated by backfill_jira_identities.rb
# - project mapping file completed by project/work-package importer
# - Jira->OpenProject role mapping file
#
# Usage:
#   bundle exec rails runner script/migration/backfill_jira_project_memberships.rb
#
# Environment variables:
#   DRY_RUN=true|false                         default: true
#   JIRA_EXPORT_DIR=/path/to/jira_export       default: /home/dev/srcs/jira_migration/jira_export
#   OUTPUT_DIR=/path/to/output                 default: <JIRA_EXPORT_DIR>/openproject_backfill
#   PROJECT_MAPPING_CSV=/path/to/project_mapping.csv
#   ROLE_MAPPING_CSV=/path/to/jira_role_mapping.csv
#   USER_MAP_CSV=/path/to/jira_user_identity_map.csv
#   GROUP_MAP_CSV=/path/to/jira_group_map.csv
#   REPLACE_MEMBER_ROLES=true|false            default: false
#   SYNC_GROUP_INHERITED_ROLES=true|false      default: true

require "csv"
require "json"
require "pathname"
require "set"
require "time"

class JiraProjectMembershipBackfill
  DEFAULT_JIRA_EXPORT_DIR = "/home/dev/srcs/jira_migration/jira_export"
  DEFAULT_OUTPUT_SUBDIR = "openproject_backfill"
  MEMBERSHIP_FILES = %w[
    project_member_roles_expanded.csv
    short_project_member_roles_expanded.csv
  ].freeze
  ACTOR_FILE = "project_role_actors_raw.csv"

  attr_reader :dry_run,
              :jira_export_dir,
              :output_dir,
              :project_mapping_csv,
              :role_mapping_csv,
              :user_map_csv,
              :group_map_csv,
              :replace_member_roles,
              :sync_group_inherited_roles

  def initialize
    @dry_run = env_true?("DRY_RUN", default: true)
    @jira_export_dir = Pathname.new(ENV.fetch("JIRA_EXPORT_DIR", DEFAULT_JIRA_EXPORT_DIR))
    @output_dir = Pathname.new(ENV.fetch("OUTPUT_DIR", jira_export_dir.join(DEFAULT_OUTPUT_SUBDIR).to_s))
    @project_mapping_csv = Pathname.new(ENV.fetch("PROJECT_MAPPING_CSV", output_dir.join("project_mapping.csv").to_s))
    @role_mapping_csv = Pathname.new(ENV.fetch("ROLE_MAPPING_CSV", output_dir.join("jira_role_mapping.csv").to_s))
    @user_map_csv = Pathname.new(ENV.fetch("USER_MAP_CSV", output_dir.join("jira_user_identity_map.csv").to_s))
    @group_map_csv = Pathname.new(ENV.fetch("GROUP_MAP_CSV", output_dir.join("jira_group_map.csv").to_s))
    @replace_member_roles = env_true?("REPLACE_MEMBER_ROLES", default: false)
    @sync_group_inherited_roles = env_true?("SYNC_GROUP_INHERITED_ROLES", default: true)

    @stats = Hash.new(0)
    @issues = []
    @applied_rows = []
    @migration_user = User.unscoped.where(type: User.name, admin: true, status: Principal.statuses[:active]).first || User.system
  end

  def run!
    validate_paths!

    puts "Starting Jira project membership backfill"
    puts "DRY_RUN=#{dry_run} REPLACE_MEMBER_ROLES=#{replace_member_roles} SYNC_GROUP_INHERITED_ROLES=#{sync_group_inherited_roles}"
    puts "JIRA_EXPORT_DIR=#{jira_export_dir}"
    puts "OUTPUT_DIR=#{output_dir}"
    puts "PROJECT_MAPPING_CSV=#{project_mapping_csv}"
    puts "ROLE_MAPPING_CSV=#{role_mapping_csv}"
    puts "USER_MAP_CSV=#{user_map_csv}"
    puts "GROUP_MAP_CSV=#{group_map_csv}"

    project_index = load_project_mapping
    role_index = load_role_mapping
    user_index = load_user_index
    group_index = load_group_index
    assignments = collect_assignments

    puts "Collected assignments: #{assignments.size}"

    assignments.each_value do |assignment|
      process_assignment(
        assignment:,
        project_index:,
        role_index:,
        user_index:,
        group_index:
      )
    end

    write_outputs
    print_summary
  end

  private

  def env_true?(name, default:)
    raw = ENV[name]
    return default if raw.nil?

    %w[1 true yes y on].include?(raw.to_s.strip.downcase)
  end

  def validate_paths!
    raise "JIRA export directory does not exist: #{jira_export_dir}" unless jira_export_dir.exist?
    raise "Missing project mapping CSV: #{project_mapping_csv}" unless project_mapping_csv.exist?
    raise "Missing role mapping CSV: #{role_mapping_csv}" unless role_mapping_csv.exist?
    raise "Missing user map CSV: #{user_map_csv}" unless user_map_csv.exist?
    raise "Missing group map CSV: #{group_map_csv}" unless group_map_csv.exist?
    raise "No admin/system user available to run membership sync" if @migration_user.nil?

    output_dir.mkpath unless output_dir.exist?
  end

  def load_project_mapping
    by_jira_key = {}
    by_jira_id = {}

    each_csv_row(project_mapping_csv) do |row|
      next unless row_enabled?(row)

      jira_key = clean(row["jira_project_key"])
      jira_id = clean(row["jira_project_id"])
      project = resolve_project_from_row(row)

      unless project
        @stats[:project_mapping_missing_target] += 1
        add_issue("project_mapping", jira_key || jira_id || "unknown", "openproject_project_not_found", row.to_h)
        next
      end

      by_jira_key[normalize(jira_key)] = project if jira_key.present?
      by_jira_id[normalize(jira_id)] = project if jira_id.present?
      @stats[:project_mapping_loaded] += 1
    end

    {
      by_jira_key:,
      by_jira_id:
    }
  end

  def resolve_project_from_row(row)
    op_project_id = integer_or_nil(row["openproject_project_id"])
    if op_project_id
      project = Project.find_by(id: op_project_id)
      return project if project
    end

    op_identifier = clean(row["openproject_project_identifier"])
    if op_identifier.present?
      project = Project.find_by(identifier: op_identifier)
      return project if project
    end

    nil
  end

  def load_role_mapping
    by_jira_role_id = {}
    by_jira_role_name = {}

    each_csv_row(role_mapping_csv) do |row|
      next unless row_enabled?(row)

      jira_role_id = clean(row["jira_role_id"])
      jira_role_name = clean(row["jira_role_name"])
      role = resolve_role_from_row(row)

      unless role
        @stats[:role_mapping_missing_target] += 1
        add_issue("role_mapping", jira_role_id || jira_role_name || "unknown", "openproject_role_not_found", row.to_h)
        next
      end

      by_jira_role_id[normalize(jira_role_id)] = role if jira_role_id.present?
      by_jira_role_name[normalize(jira_role_name)] = role if jira_role_name.present?
      @stats[:role_mapping_loaded] += 1
    end

    {
      by_jira_role_id:,
      by_jira_role_name:
    }
  end

  def resolve_role_from_row(row)
    role_id = integer_or_nil(row["openproject_role_id"])
    if role_id
      role = Role.find_by(id: role_id)
      return role if valid_project_role?(role)
    end

    role_name = clean(row["openproject_role_name"]) || clean(row["recommended_openproject_role_name"])
    if role_name.present?
      role = Role.find_by("LOWER(name) = ?", normalize(role_name))
      return role if valid_project_role?(role)
    end

    nil
  end

  def valid_project_role?(role)
    role.present? && role.member? && role.is_a?(ProjectRole)
  end

  def load_user_index
    by_user_key = {}
    by_username = {}
    by_email = {}

    each_csv_row(user_map_csv) do |row|
      user_id = integer_or_nil(row["openproject_user_id"])
      next unless user_id

      user = User.unscoped.where(type: User.name).find_by(id: user_id)
      next unless user

      user_key = clean(row["jira_user_key"])
      username = clean(row["jira_username"])
      email = clean(row["jira_email"])

      by_user_key[normalize(user_key)] = user_id if user_key.present?
      by_username[normalize(username)] = user_id if username.present?
      by_email[normalize(email)] = user_id if email.present?
      @stats[:user_mapping_loaded] += 1
    end

    {
      by_user_key:,
      by_username:,
      by_email:
    }
  end

  def load_group_index
    by_group_name = {}

    each_csv_row(group_map_csv) do |row|
      group_id = integer_or_nil(row["openproject_group_id"])
      group_name = clean(row["jira_group_name"])
      next unless group_id && group_name.present?

      group = Group.unscoped.find_by(id: group_id)
      next unless group

      by_group_name[normalize(group_name)] = group_id
      @stats[:group_mapping_loaded] += 1
    end

    {
      by_group_name:
    }
  end

  def collect_assignments
    assignments = {}

    MEMBERSHIP_FILES.each do |filename|
      path = jira_export_dir.join(filename)
      next unless path.exist?

      each_csv_row(path) do |row|
        append_membership_row(assignments, row, filename)
      end
    end

    actor_path = jira_export_dir.join(ACTOR_FILE)
    if actor_path.exist?
      each_csv_row(actor_path) do |row|
        append_actor_row(assignments, row, ACTOR_FILE)
      end
    end

    assignments
  end

  def append_membership_row(assignments, row, source_file)
    project_key = clean(row["project_key"])
    project_id = clean(row["project_id"])
    role_id = clean(row["role_id"])
    role_name = clean(row["role_name"])
    return if project_key.blank? && project_id.blank?
    return if role_id.blank? && role_name.blank?

    membership_source = normalize(row["membership_source"])
    source_group = clean(row["source_group"])

    principal = if source_group.present? && membership_source.include?("group")
                  { type: "group", ref_type: "name", ref_value: source_group }
                else
                  user_principal_from_row(
                    user_key: clean(row["user_key"]),
                    username: clean(row["username"]),
                    email: clean(row["email_address"])
                  )
                end
    return unless principal

    append_assignment(
      assignments:,
      project_key:,
      project_id:,
      principal:,
      role_id:,
      role_name:,
      source_file:
    )
  end

  def append_actor_row(assignments, row, source_file)
    project_key = clean(row["project_key"])
    project_id = clean(row["project_id"])
    role_id = clean(row["role_id"])
    role_name = clean(row["role_name"])
    return if project_key.blank? && project_id.blank?
    return if role_id.blank? && role_name.blank?

    actor_type = normalize(row["actor_type"])

    principal = if actor_type.include?("group")
                  actor_name = clean(row["actor_name"])
                  actor_name.present? ? { type: "group", ref_type: "name", ref_value: actor_name } : nil
                elsif actor_type.include?("user")
                  user_principal_from_row(
                    user_key: clean(row["expanded_user_key"]),
                    username: clean(row["expanded_user_username"]) || clean(row["actor_name"]),
                    email: clean(row["expanded_user_email"])
                  )
                end
    return unless principal

    append_assignment(
      assignments:,
      project_key:,
      project_id:,
      principal:,
      role_id:,
      role_name:,
      source_file:
    )
  end

  def user_principal_from_row(user_key:, username:, email:)
    if user_key.present?
      { type: "user", ref_type: "user_key", ref_value: user_key, username:, email: }
    elsif username.present?
      { type: "user", ref_type: "username", ref_value: username, username:, email: }
    elsif email.present?
      { type: "user", ref_type: "email", ref_value: email, username:, email: }
    end
  end

  def append_assignment(assignments:, project_key:, project_id:, principal:, role_id:, role_name:, source_file:)
    key = [
      normalize(project_key),
      normalize(project_id),
      principal.fetch(:type),
      principal.fetch(:ref_type),
      normalize(principal.fetch(:ref_value))
    ].join("|")

    row = (assignments[key] ||= {
      key:,
      project_key:,
      project_id:,
      principal: principal.dup,
      role_refs: Set.new,
      source_files: Set.new
    })

    row[:role_refs] << [normalize(role_id), normalize(role_name)]
    row[:source_files] << source_file
  end

  def process_assignment(assignment:, project_index:, role_index:, user_index:, group_index:)
    project = resolve_project(assignment, project_index)
    return unless project

    principal = resolve_principal(assignment[:principal], user_index:, group_index:)
    return unless principal

    target_roles = resolve_target_roles(assignment[:role_refs], role_index, assignment)
    if target_roles.empty?
      @stats[:assignments_skipped_no_mapped_role] += 1
      add_issue("assignment", assignment[:key], "mapped_role_missing", issue_payload(assignment))
      return
    end

    apply_membership(
      project:,
      principal:,
      target_role_ids: target_roles,
      assignment:
    )
  rescue StandardError => e
    @stats[:assignments_failed] += 1
    add_issue("assignment", assignment[:key], e.message, issue_payload(assignment))
  end

  def resolve_project(assignment, project_index)
    project = nil

    project_key = normalize(assignment[:project_key])
    project_id = normalize(assignment[:project_id])
    project = project_index[:by_jira_key][project_key] if project_key.present?
    project ||= project_index[:by_jira_id][project_id] if project_id.present?

    return project if project

    @stats[:assignments_missing_project_mapping] += 1
    add_issue("assignment", assignment[:key], "project_mapping_not_found", issue_payload(assignment))
    nil
  end

  def resolve_principal(principal_ref, user_index:, group_index:)
    if principal_ref[:type] == "group"
      resolve_group_principal(principal_ref, group_index)
    else
      resolve_user_principal(principal_ref, user_index)
    end
  end

  def resolve_group_principal(principal_ref, group_index)
    key = normalize(principal_ref[:ref_value])
    group_id = group_index[:by_group_name][key]
    group = Group.unscoped.find_by(id: group_id) if group_id
    group ||= Group.unscoped.where("LOWER(lastname) = ?", key).first

    unless group
      @stats[:assignments_missing_group] += 1
      add_issue("assignment", key, "group_not_found", principal_ref)
      return nil
    end

    group
  end

  def resolve_user_principal(principal_ref, user_index)
    user_id = nil

    case principal_ref[:ref_type]
    when "user_key"
      user_id = user_index[:by_user_key][normalize(principal_ref[:ref_value])]
    when "username"
      user_id = user_index[:by_username][normalize(principal_ref[:ref_value])]
    when "email"
      user_id = user_index[:by_email][normalize(principal_ref[:ref_value])]
    end

    if user_id.nil?
      user_id = user_index[:by_username][normalize(principal_ref[:username])] if principal_ref[:username].present?
      user_id = user_index[:by_email][normalize(principal_ref[:email])] if user_id.nil? && principal_ref[:email].present?
    end

    user = User.unscoped.where(type: User.name).find_by(id: user_id) if user_id
    if user.nil? && principal_ref[:email].present?
      user = User.unscoped.where(type: User.name).where("LOWER(mail) = ?", normalize(principal_ref[:email])).first
    end

    unless user
      @stats[:assignments_missing_user] += 1
      add_issue("assignment", principal_ref[:ref_value], "user_not_found", principal_ref)
      return nil
    end

    user
  end

  def resolve_target_roles(role_refs, role_index, assignment)
    role_ids = Set.new

    role_refs.each do |role_id_ref, role_name_ref|
      role = nil
      role = role_index[:by_jira_role_id][role_id_ref] if role_id_ref.present?
      role ||= role_index[:by_jira_role_name][role_name_ref] if role_name_ref.present?

      if role.nil?
        @stats[:assignments_unmapped_role_ref] += 1
        add_issue(
          "assignment_role",
          assignment[:key],
          "role_mapping_not_found",
          { jira_role_id: role_id_ref, jira_role_name: role_name_ref }
        )
        next
      end

      role_ids << role.id
    end

    role_ids
  end

  def apply_membership(project:, principal:, target_role_ids:, assignment:)
    member = Member.find_or_initialize_by(
      project_id: project.id,
      user_id: principal.id,
      entity_type: nil,
      entity_id: nil
    )

    new_member = member.new_record?
    if new_member
      if dry_run
        @stats[:members_would_create] += 1
      else
        member.save!(validate: false)
        @stats[:members_created] += 1
      end
    else
      @stats[:members_existing] += 1
    end

    existing_direct_role_ids = member.member_roles.where(inherited_from: nil).pluck(:role_id).to_set
    roles_to_add = target_role_ids - existing_direct_role_ids
    roles_to_remove = replace_member_roles ? (existing_direct_role_ids - target_role_ids) : Set.new

    if dry_run
      @stats[:member_roles_would_add] += roles_to_add.size
      @stats[:member_roles_would_remove] += roles_to_remove.size
    else
      roles_to_add.each do |role_id|
        MemberRole.find_or_create_by!(member_id: member.id, role_id:, inherited_from: nil)
      end

      if roles_to_remove.any?
        member.member_roles.where(inherited_from: nil, role_id: roles_to_remove.to_a).delete_all
      end

      @stats[:member_roles_added] += roles_to_add.size
      @stats[:member_roles_removed] += roles_to_remove.size
    end

    sync_group_memberships_if_needed(
      principal:,
      member:,
      new_member:,
      roles_to_add:,
      roles_to_remove:
    )

    action = if new_member
               dry_run ? "would_create_member" : "created_member"
             elsif roles_to_add.any? || roles_to_remove.any?
               dry_run ? "would_update_roles" : "updated_roles"
             else
               "noop"
             end

    @stats[:assignments_processed] += 1
    @applied_rows << {
      jira_project_key: assignment[:project_key],
      jira_project_id: assignment[:project_id],
      principal_type: principal.class.name,
      principal_id: principal.id,
      principal_label: principal_label(principal),
      jira_roles: assignment[:role_refs].map { |role_id, role_name| "#{role_id}:#{role_name}" }.sort.join(";"),
      openproject_project_id: project.id,
      applied_role_ids: target_role_ids.to_a.sort.join(";"),
      action:,
      source_files: assignment[:source_files].to_a.sort.join(";")
    }
  end

  def sync_group_memberships_if_needed(principal:, member:, new_member:, roles_to_add:, roles_to_remove:)
    return unless sync_group_inherited_roles
    return if dry_run
    return unless principal.is_a?(Group)
    return if !new_member && roles_to_add.empty? && roles_to_remove.empty?

    Groups::CreateInheritedRolesService
      .new(principal, current_user: @migration_user, contract_class: EmptyContract)
      .call(user_ids: principal.user_ids, project_ids: [member.project_id], message: "Jira membership backfill")

    Groups::UpdateRolesService
      .new(principal, current_user: @migration_user, contract_class: EmptyContract)
      .call(member:, send_notifications: false, message: "Jira membership backfill")

    @stats[:group_inherited_role_syncs] += 1
  rescue StandardError => e
    @stats[:group_inherited_role_sync_failures] += 1
    add_issue("group_sync", principal.id.to_s, e.message, { member_id: member.id, project_id: member.project_id })
  end

  def write_outputs
    write_applied_rows
    write_issues
    write_summary
  end

  def write_applied_rows
    path = output_dir.join("project_membership_backfill_applied.csv")
    headers = %w[
      jira_project_key
      jira_project_id
      principal_type
      principal_id
      principal_label
      jira_roles
      openproject_project_id
      applied_role_ids
      action
      source_files
    ]

    CSV.open(path, "wb", headers:, write_headers: true) do |csv|
      @applied_rows.each do |row|
        csv << headers.map { |header| row[header.to_sym] }
      end
    end
  end

  def write_issues
    path = output_dir.join("project_membership_backfill_issues.csv")
    headers = %w[type context reason payload_json]

    CSV.open(path, "wb", headers:, write_headers: true) do |csv|
      @issues.each do |issue|
        csv << [issue[:type], issue[:context], issue[:reason], JSON.generate(issue[:payload])]
      end
    end
  end

  def write_summary
    path = output_dir.join("project_membership_backfill_summary.json")
    payload = {
      generated_at_utc: Time.now.utc.iso8601,
      dry_run:,
      jira_export_dir: jira_export_dir.to_s,
      output_dir: output_dir.to_s,
      stats: @stats.sort.to_h,
      issues_count: @issues.size
    }

    path.write(JSON.pretty_generate(payload))
  end

  def print_summary
    puts "Project membership backfill summary:"
    @stats.sort.each do |key, value|
      puts "  #{key}: #{value}"
    end
    puts "  issues: #{@issues.size}"
    puts "Output:"
    puts "  #{output_dir.join('project_membership_backfill_applied.csv')}"
    puts "  #{output_dir.join('project_membership_backfill_issues.csv')}"
    puts "  #{output_dir.join('project_membership_backfill_summary.json')}"
    puts(dry_run ? "Dry run complete. No DB rows were changed." : "Backfill complete.")
  end

  def issue_payload(assignment)
    {
      project_key: assignment[:project_key],
      project_id: assignment[:project_id],
      principal: assignment[:principal],
      role_refs: assignment[:role_refs].to_a
    }
  end

  def add_issue(type, context, reason, payload)
    @issues << {
      type:,
      context:,
      reason:,
      payload:
    }
  end

  def principal_label(principal)
    if principal.is_a?(Group)
      principal.lastname
    else
      "#{principal.login} <#{principal.mail}>"
    end
  end

  def each_csv_row(path, &block)
    CSV.foreach(path, headers: true, encoding: "bom|utf-8", &block)
  end

  def row_enabled?(row)
    enabled = clean(row["enabled"])
    return true if enabled.blank?

    !%w[false 0 no n].include?(normalize(enabled))
  end

  def clean(value)
    value.to_s.strip.presence
  end

  def normalize(value)
    value.to_s.strip.downcase
  end

  def integer_or_nil(value)
    Integer(value)
  rescue ArgumentError, TypeError
    nil
  end
end

JiraProjectMembershipBackfill.new.run!
