name: Docker / Scheduled builds

on:
  # build dev and release branches daily
  schedule:
    - cron: "20 2 * * *" # Daily at 02:20
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    strategy:
      matrix:
        include:
          - branch: dev
            tag: "dev"
          - branch: release/16.3
            tag: "16.3-pre"
    uses: ./.github/workflows/docker.yml
    with:
      branch: ${{ matrix.branch }}
      tag: ${{ matrix.tag }}
    secrets: inherit